apiVersion: v1
kind: Service
metadata:
  name: hello-graphql
  labels:
    app: hello-graphql
    tier: backend
spec:
  selector:
    app: hello-graphql
    tier: backend
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-graphql
spec:
  selector:
    matchLabels:
      app: hello-graphql
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-graphql
        tier: backend
    spec:
      containers:
      - name: hello-graphql
        image: aaronnbrock/hello-graphql:0.0.2-9-g3d5fd7a
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
